version: '3'
services:
  ghost:
    image: ghost:1-alpine
    container_name: ghost-blog
    restart: always
    ports:
     - 80:2368
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: Password!
      database__connection__database: ghost
    volumes:
      - ghost-volume:/var/lib/ghost
    depends_on:
      - mysql

  mysql:
   image: mysql:5.7
   container_name: ghost-db
   restart: always
   environment: 
    MYSQL_ROOT_PASSWORD: Password!
   volumes:
     - mysql-volume:/var/lib/mysql

volumes:
  ghost-volume:
  mysql-volume:
